"""
In Silico Heart Models - mat2fem.py
Original by Vilde N. Strom, July 2017 - Simula Research Laboratory
Python 3 compatible rewrite with graceful error handling.
"""

import os
import sys
import shutil
import datetime
import subprocess
import json

now = datetime.datetime.now()
time_str = now.strftime("%d.%m-%H.%M")
Date = 'Data-' + time_str  # name of output folder

# Assigning variable names to important folders
root     = os.getcwd()  # path to In_Silico_Heart_Models
mat_data = root + '/Matlab_Process/Data/'
mat_scar = mat_data + 'ScarImages/MetaImages'
mat_txt  = mat_data + 'Texts'
mat_seg  = mat_data + 'Seg/'
surf     = root + '/Surfaces/' + Date
vtk_srf  = surf + '/vtkFiles'
msh_srf  = surf + '/mshFiles'
fem      = root + '/FEM/' + Date
conv     = root + '/Convertion_Process'
scar     = root + '/Scar_Process'
script   = root + '/scripts/'
gmsh_exe = 'gmsh'
config_path = os.path.join(root, 'web_interface', 'config.json')
if os.path.exists(config_path):
    try:
        with open(config_path) as f:
            cfg = json.load(f)
            gmsh_exe = cfg.get('gmsh_path', 'gmsh')
            print(f"Using configured Gmsh: {gmsh_exe}")
    except: pass

# ──────────────────────────────────────────────────────────────
# PART 1: MATLAB SLICE ALIGNMENT
# ──────────────────────────────────────────────────────────────

def run_matlab(nr_errors, err_list):
    """Run MATLAB alignment script. Skips gracefully if MATLAB not found."""
    ret = os.system('bash run_matlab.sh')
    if ret != 0:
        print("WARNING: MATLAB returned non-zero exit code. "
              "If MATLAB is not installed, Parts 2 & 3 need pre-existing text files.")
        return
    scar_files = [f for f in os.listdir(mat_scar + '/') if not f.startswith('.')]
    N2 = len(scar_files)
    if (N - nr_errors) * 2 > N2:  # not all .mat files processed
        remove_error(N2, nr_errors, err_list)


def remove_error(N2, nr_errors, err_list):
    """Remove errored patient file and retry."""
    error = (N2 + nr_errors * 2) // 2 + 1
    err_path = '{}Patient_{}.mat'.format(mat_seg, error)
    if os.path.exists(err_path):
        os.remove(err_path)
        nr_errors += 1
        err_list.append(error)
        run_matlab(nr_errors, err_list)
    else:
        print('End of patients or MATLAB error for Patient_{}.'.format(error))


def remove_error_files(fname):
    """Delete any text files generated by an errored patient."""
    for part in ['LVEndo', 'LVEpi', 'RVEndo', 'RVEpi']:
        path = '{}/{}-{}-Frame_1.txt'.format(mat_txt, fname, part)
        if os.path.isfile(path):
            os.remove(path)


# Collect .mat files from seg/
source = '{}/seg/'.format(root)
if not os.path.isdir(source):
    print("ERROR: seg/ directory not found at", source)
    sys.exit(1)

files = [f for f in os.listdir(source)
         if f.endswith('.mat') and not f.startswith('.')]
N = len(files)
print('Found {} patient file(s) in seg/'.format(N))

nr_errors = 0
err_list  = []

# Copy .mat files to Matlab_Process/Data/Seg/
os.makedirs(mat_seg, exist_ok=True)
for f in files:
    shutil.copy(source + f, mat_seg + f)

# Run MATLAB (skips if not installed)
os.chdir('Matlab_Process')
run_matlab(nr_errors, err_list)

if err_list:
    for nr in err_list:
        fname = 'Patient_{}'.format(nr)
        remove_error_files(fname)
        print('{} was removed due to errors. Continuing without it.'.format(fname))

print('PART 1 DONE: SLICES ALIGNED')
os.chdir(root)

# ──────────────────────────────────────────────────────────────
# PART 2: SURFACE GENERATION
# ──────────────────────────────────────────────────────────────

def move_files(src, dst):
    """Move all files from src directory to dst directory."""
    os.makedirs(dst, exist_ok=True)
    for f in os.listdir(src):
        shutil.move(os.path.join(src, f), os.path.join(dst, f))


def run_script(path, script_name):
    """Run a bash script in a given directory."""
    os.chdir(path)
    ret = os.system('bash {}'.format(script_name))
    os.chdir(root)
    return ret


def remove_dir_files(folder_list):
    """Remove all files inside each listed sub-folder."""
    for folder in folder_list:
        full = mat_data + folder
        if os.path.isdir(full):
            for f in os.listdir(full):
                fp = os.path.join(full, f)
                if os.path.isfile(fp):
                    os.remove(fp)


# Create output folder for surface data
print('Creating folder {} for data storage'.format(Date))
os.makedirs(surf, exist_ok=True)

# Check if text files exist (output from MATLAB step)
txt_files = [f for f in os.listdir(mat_txt) if not f.startswith('.')] \
            if os.path.isdir(mat_txt) else []

if not txt_files:
    print("WARNING: No text files found in Matlab_Process/Data/Texts/.")
    print("         MATLAB alignment may not have run. Skipping surface generation.")
    print("         Parts 1 & 2 require MATLAB output to proceed.")
else:
    # Move files
    move_files(mat_txt, conv)
    move_files(mat_scar, scar + '/Data')
    remove_dir_files(['Aligned/', 'Seg/'])

    # Generate heart surfaces
    print('Making surfaces...')
    run_script(conv, 'make_surface_all.sh')

    print('Moving surface files to Surfaces/')
    for folder in ['plyFiles', 'vtkFiles', 'txtFiles']:
        src_path = os.path.join(conv, 'Data', folder)
        dst_path = os.path.join(surf, folder)
        if os.path.isdir(src_path):
            os.makedirs(dst_path, exist_ok=True)
            move_files(src_path, dst_path)

    # Generate scar surfaces
    print('Making scar surfaces...')
    run_script(scar, 'run.sh')

    print('Moving scar files to Surfaces/')
    scar_data = scar + '/Data'
    if os.path.isdir(scar_data):
        for f in os.listdir(scar_data):
            fp = os.path.join(scar_data, f)
            if f.endswith('.vtk'):
                shutil.move(fp, os.path.join(vtk_srf, f))
            else:
                if os.path.isfile(fp):
                    os.remove(fp)

print('PART 2 DONE: MAKING SURFACES')

# ──────────────────────────────────────────────────────────────
# PART 3: GENERATION OF FEM FILES
# ──────────────────────────────────────────────────────────────

os.makedirs(msh_srf, exist_ok=True)
os.makedirs(fem, exist_ok=True)

rem_script = '{}remove_site_times.py'.format(script)
if os.path.isfile(rem_script):
    shutil.copyfile(rem_script, fem + '/remove_site_times.py')


def mergevtk(i, msh_dir, vtk_dir):
    """Generate .msh file from VTK surfaces using Gmsh."""
    lv_endo  = '{}/Patient_{}-LVEndo-Frame_1.vtk'.format(vtk_dir, i)
    rv_endo  = '{}/Patient_{}-RVEndo-Frame_1.vtk'.format(vtk_dir, i)
    rv_epi   = '{}/Patient_{}-RVEpi-Frame_1.vtk'.format(vtk_dir, i)
    msh      = '{}/Patient_{}.msh'.format(msh_dir, i)
    out_log  = '{}/Patient_{}.out.txt'.format(msh_dir, i)
    biv_mesh = '{}/scripts/biv_mesh.geo'.format(root)

    cmd = '{} -3 {} -merge {} {} {} -o {} > {} 2>&1'.format(
        gmsh_exe, lv_endo, rv_endo, rv_epi, biv_mesh, msh, out_log)
    os.system(cmd)


def write_fem(input_file, outputname):
    """Generate .pts, .elem and .tris files from a .msh file."""
    if not os.path.isfile(input_file):
        print('WARNING: {} not found, skipping.'.format(input_file))
        return
    with open(input_file, 'r') as infile:
        lines = infile.readlines()

    pts_lines, elem_lines, tris_lines = [], [], []
    in_nodes = in_elems = False

    for line in lines:
        words = line.split()
        if not words:
            continue
        if words[0] == '$Nodes':
            in_nodes = True; continue
        if words[0] == '$EndNodes':
            in_nodes = False; continue
        if words[0] == '$Elements':
            in_elems = True; continue
        if words[0] == '$EndElements':
            in_elems = False; continue

        if in_nodes:
            if len(words) == 1:
                pts_lines.append(words[0] + '\n')
            else:
                pts_lines.append('{} {} {}\n'.format(words[1], words[2], words[3]))

        if in_elems:
            if len(words) == 1:
                elem_lines.append(words[0] + '\n')
            elif len(words) > 7:
                ii = int(words[5]) - 1
                jj = int(words[6]) - 1
                kk = int(words[7]) - 1
                if words[1] == '2':
                    tris_lines.append('{} {} {} 1\n'.format(ii, jj, kk))
                elif words[1] == '4':
                    ll = int(words[8]) - 1
                    elem_lines.append('Tt {} {} {} {} 1\n'.format(ii, jj, kk, ll))

    with open(outputname + '.pts',  'w') as f: f.writelines(pts_lines)
    with open(outputname + '.elem', 'w') as f: f.writelines(elem_lines)
    with open(outputname + '.tris', 'w') as f: f.writelines(tris_lines)


def write_files(pat_path, i):
    """Copy simulation config files into patient folder."""
    for fname in ['stim_coord.dat', 'base.par']:
        src = script + fname
        if os.path.isfile(src):
            shutil.copyfile(src, pat_path + '/' + fname)

    rs_src = script + 'risk_strat_1_16.sh'
    if os.path.isfile(rs_src):
        infile_lines = open(rs_src, 'r').readlines()
        with open(pat_path + '/risk_strat_1_16.sh', 'w') as outfile:
            new_jobid = '#SBATCH --job-name=Pat_{}'.format(i)
            for idx, line in enumerate(infile_lines):
                outfile.write(new_jobid + '\n' if idx == 2 else line)


# Process each patient
patients_processed = 0
for i in range(1, N + 1):
    vtk_path = '{}/Patient_{}_scar.vtk'.format(vtk_srf, i)
    if os.path.isfile(vtk_path):
        mergevtk(i, msh_srf, vtk_srf)
        print('Generated .msh file for Patient {}.'.format(i))

        write_fem('{}/Patient_{}.msh'.format(msh_srf, i), 'Patient_{}'.format(i))
        print('Generated .tris, .elem and .pts for Patient {}.'.format(i))

        patient_path = '{}/Patient_{}'.format(fem, i)
        os.makedirs(patient_path, exist_ok=True)
        for j in ['tris', 'elem', 'pts']:
            src_f = 'Patient_{}.{}'.format(i, j)
            dst_f = '{}/Patient_{}.{}'.format(patient_path, i, j)
            if os.path.isfile(src_f):
                os.rename(src_f, dst_f)

        write_files(patient_path, i)
        patients_processed += 1
    else:
        print('Patient {} VTK not found — skipping FEM generation.'.format(i))

print('All FEM files stored in FEM/{}'.format(Date))
print('PART 3 DONE: GENERATED {} FEM MODEL(S)'.format(patients_processed))